## scaffolding based on high-order contacts

Pore-C can capture the high-order contacts, which allow us to use this information to order and orientate the contigs.

The allhic optimize used the distance of paired hic mapping between two contigs, inspired of this, we use distance of pore-c fragments to calculate the score of contigs position.


### Testing
We created several pore-c alignments and five contigs to test our methods

tig1 -> tig2 -> tig3 -> tig4 -> tig5

In [33]:
import random 
from itertools import product, combinations
from functools import reduce

import numpy as np
import operator 


In [49]:
contig_sizes = {
    "tig1": 10000,
    "tig2": 7000,
    "tig3": 12000,
    "tig4": 5000,
    "tig5": 8000,
}
pore_c_alignments = {
    "read1": [("tig1", 8000, 9000), ("tig2", 1000, 1500), ("tig3", 100, 400),],
    "read2": [("tig1", 7000, 7500), ("tig2", 2000, 3000)],
    "read3": [("tig1", 8000, 9000), ("tig2", 1000, 1500), ("tig2", 500, 900),],
    "read4": [("tig1", 8000, 9000), ("tig3", 500, 900),],
    "read5": [("tig2", 5000, 7000), ("tig2", 6000, 6500), ("tig3", 1000, 2000), ("tig3", 2000, 3000)],
    "read6": [("tig2", 6000, 6500), ("tig4", 1000, 2000), ("tig5", 2000, 3000)],
    "read7": [("tig4",1000, 1500), ("tig5", 1000, 2000), ("tig5", 2000, 3000)],
}

class Contig:
    def __init__(self, contig, bin_count, position=0, orientation=0, ):
        self.contig = contig 
        self.position = position 
        self.orientation = orientation 
        self.bin_count = bin_count

class Contigs:
    def __init__(self, contigs):
        self.data = contigs
    
    def orders(self):
        res = [contig.position for contig in self.data]
        return res 

    def score(self):
        for contig in self.data:
            pass 
    
class Alignments:
    def __init__(self, alignments, binsize=100):
        self.data = alignments
        self.binsize = binsize
        self.order = len(alignments)
        self.distances = self.calculate_distance()

    def calculate_distance(self):
        l = list(combinations(range(self.order), 2))
        distances = np.zeros(shape=(self.order, self.order))
        for i, j in l:
            distances[i, j] = (self.data[i][2] + self.data[j][1]) // self.binsize // 2
        
        return distances 
    
    def get_distance_by_order(self):
        pass 
    
    

        
random.seed(12345)
    
contigs = []

tigs = list(contig_sizes.keys())
random.shuffle(tigs)
for i, contig in enumerate(tigs):
    bin_count = contig_sizes[contig] // 100 
    orientation = random.sample([0, 1], 1)
    contigs.append(Contig(contig, bin_count, i,  orientation))

for read in pore_c_alignments:
    alignments = pore_c_alignments[read]
    # random.shuffle(alignments)
    am =  Alignments(alignments)
    print(am.distances)

[[ 0. 50. 45.]
 [ 0.  0.  8.]
 [ 0.  0.  0.]]
[[ 0. 47.]
 [ 0.  0.]]
[[ 0. 50. 47.]
 [ 0.  0. 10.]
 [ 0.  0.  0.]]
[[ 0. 47.]
 [ 0.  0.]]
[[ 0. 65. 40. 45.]
 [ 0.  0. 37. 42.]
 [ 0.  0.  0. 20.]
 [ 0.  0.  0.  0.]]
[[ 0. 37. 42.]
 [ 0.  0. 20.]
 [ 0.  0.  0.]]
[[ 0. 12. 17.]
 [ 0.  0. 20.]
 [ 0.  0.  0.]]
